export interface PortfolioItem {
  id: string
  title: string
  description: string
  category: "logos" | "posters" | "social-media" | "presentations" | "websites"
  image: string // Main thumbnail image
  images?: string[] // Array of additional images for detailed view
  technologies: string[]
  year: string
  liveUrl?: string
  githubUrl?: string
}

export const portfolioData: PortfolioItem[] = [
  // Logos
  {
    id: "1",
    title: "Beads Shop Logo – Classic Design",
    description: "Elegant and handcrafted logo design tailored for a beads shop, highlighting the artistry and cultural roots of traditional jewelry.",
    category: "logos",
    image: "/logo1.png?height=300&width=400",
    technologies: ["Adobe Illustrator", "Canva"],
    year: "2024",
  },
  {
    id: "2",
    title: "Beads Shop Logo – Modern Identity",
    description: "Contemporary brand identity concept for a beads shop, combining minimalism with vibrant color tones to appeal to modern customers.",
    category: "logos",
    image: "/logo2.png?height=300&width=400",
    technologies: ["Adobe Illustrator", "Photoshop"],
    year: "2024",
  },
  {
    id: "3",
    title: "Jabon de Lofah – Organic Soap Logo",
    description: "Fresh and natural logo design for Jabon de Lofah, an organic soap brand, reflecting purity, wellness, and eco-friendly values.",
    category: "logos",
    image: "/logo3.png?height=300&width=400",
    technologies: ["Figma", "Adobe Illustrator"],
    year: "2023",
  },

  // Posters
  {
    id: "4",
    title: "Website Development Course Poster",
    description: "Promotional poster designed to attract students for a website development class, showcasing course benefits, duration, and registration details.",
    category: "posters",
    image: "/poster1.png?height=300&width=400",
    technologies: ["Canva"],
    year: "2024",
  },
  {
    id: "5",
    title: "Get-Together Invitation Poster",
    description: "Creative and lively invitation poster for a friends and family get-together event, featuring playful visuals and an inviting tone.",
    category: "posters",
    image: "/poster2.png?height=300&width=400",
    technologies: ["Canva"],
    year: "2024",
  },
  {
    id: "6",
    title: "Minimal Wedding Invitation Design",
    description: "A modern and minimalist wedding invitation poster featuring subtle colors, clean layout, and a touch of elegance for a stylish celebration.",
    category: "posters",
    image: "/poster3.png?height=300&width=400",
    technologies: ["Canva"],
    year: "2023",
  },
  {
    id: "18",
    title: "Canvas Modal UI Mockup",
    description: "Poster-style visual mockup showcasing a canvas modal UI component, demonstrating layout design and interaction flow.",
    category: "posters",
    image: "/poster4.png?height=300&width=400",
    technologies: ["Adobe Creative Suite"],
    year: "2023",
  },
  // Social Media
  {
    id: "7",
    title: "LinkedIn Post Series",
    description: "Engaging LinkedIn post templates for business content, designed for maximum reach.",
    category: "social-media",
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=400&width=600&text=LinkedIn+Post+1",
      "/placeholder.svg?height=400&width=600&text=LinkedIn+Post+2",
      "/placeholder.svg?height=400&width=600&text=LinkedIn+Post+3",
    ],
    technologies: ["Canva", "Figma"],
    year: "2024",
  },
  {
    id: "8",
    title: "Instagram Story Templates",
    description: "Branded Instagram story templates for social media marketing, dynamic and interactive.",
    category: "social-media",
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=400&width=600&text=Instagram+Story+1",
      "/placeholder.svg?height=400&width=600&text=Instagram+Story+2",
    ],
    technologies: ["Canva", "Adobe Photoshop"],
    year: "2024",
  },
  {
    id: "9",
    title: "Facebook Ad Campaign",
    description: "Social media graphics for Facebook advertising campaign, optimized for conversions.",
    category: "social-media",
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=400&width=600&text=Facebook+Ad+1",
      "/placeholder.svg?height=400&width=600&text=Facebook+Ad+2",
    ],
    technologies: ["Canva", "Figma"],
    year: "2023",
  },

  // Presentations
  {
    id: "10",
    title: "Ismail Industries Ltd.",
    description: "Professional presentation for University project , visually compelling and informative.",
    category: "presentations",
    image: "/ismail1.png?height=300&width=400",
    images: [
      "/ismail1.png?height=400&width=600&text=Pitch+Deck+Slide+1",
      "/ismail2.png?height=400&width=600&text=Pitch+Deck+Slide+2",
      "/ismail3.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail4.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail5.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail6.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail7.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail8.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail9.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail10.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail11.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail12.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail13.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail14.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail15.png?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail16.png?height=400&width=600&text=Pitch+Deck+Slide+3",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2024",
  },
  {
    id: "11",
    title: "Anger Managment Presentation",
    description: "Anger Management For University Project Showing Visual Representation Of Anger Management",
    category: "presentations",
    image: "/anger1.png?height=300&width=400",
    images: [
      "/anger1.png?height=400&width=600&text=Sales+Presentation+1",
      "/anger2.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger3.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger4.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger5.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger6.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger7.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger8.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger9.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger10.png?height=400&width=600&text=Sales+Presentation+2",
      "/anger11.png?height=400&width=600&text=Sales+Presentation+2",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2024",
  },
  {
    id: "17",
    title: "Entrepreneurial Product Pitch – Jabon da Lofah",
    description: "A persuasive and visually engaging presentation showcasing the innovation, benefits, and market potential of Jabon da Lofah – a natural exfoliating soap designed for modern self-care.",
    category: "presentations",
    image: "/jabon1.png?height=300&width=400",
    images: [
      "/jabon1.png?height=400&width=600&text=Sales+Presentation+1",
      "/jabon2.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon3.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon4.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon5.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon6.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon7.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon8.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon9.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon10.png?height=400&width=600&text=Sales+Presentation+2",
      "/jabon11c.png?height=400&width=600&text=Sales+Presentation+2",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2024",
  },
  {
    id: "12",
    title: "Consumer Behavior Analysis – Rooh Afza",
    description: "An insightful presentation exploring consumer preferences, cultural relevance, and purchasing behavior related to Rooh Afza – the iconic herbal drink that has shaped generations of refreshment habits.",
    category: "presentations",
    image: "/rooh1.png?height=300&width=400",
    images: [
      "/rooh1.png?height=400&width=600&text=Training+Slides+2",
      "/rooh2.png?height=400&width=600&text=Training+Slides+2",
      "/rooh3.png?height=400&width=600&text=Training+Slides+2",
      "/rooh4.png?height=400&width=600&text=Training+Slides+2",
      "/rooh5.png?height=400&width=600&text=Training+Slides+2",
      "/rooh6.png?height=400&width=600&text=Training+Slides+2",
      "/rooh7.png?height=400&width=600&text=Training+Slides+2",
      "/rooh8.png?height=400&width=600&text=Training+Slides+2",
      "/rooh9.png?height=400&width=600&text=Training+Slides+2",
      "/rooh10.png?height=400&width=600&text=Training+Slides+2",
      "/rooh11.png?height=400&width=600&text=Training+Slides+2",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2023",
  },


  // Websites
  {
    id: "13",
    title: "Cake Town Website ",
    description: "Cke Town website showcasing the product and services they offer, responsive .",
    category: "websites",
    image: "/cake1.png?height=300&width=400",
    images: [
      "/cake1.png?height=400&width=600&text=E-commerce+Homepage",
      "/cake2.png?height=400&width=600&text=Product+Page",
      "/cake3.png?height=400&width=600&text=Product+Page",
      "/cake4.png?height=400&width=600&text=Product+Page",
      "/cake5.png?height=400&width=600&text=Product+Page",
      "/cake6.png?height=400&width=600&text=Product+Page",
      "/cake7.png?height=400&width=600&text=Product+Page",
      "/cake8.png?height=400&width=600&text=Product+Page",
      "/cake9.png?height=400&width=600&text=Product+Page",
      "/cake10.png?height=400&width=600&text=Product+Page",
      "/cake11.png?height=400&width=600&text=Checkout+Flow",
      "/cake12.png?height=400&width=600&text=Checkout+Flow",
      "/cake13.png?height=400&width=600&text=Checkout+Flow",
      "/cake14.png?height=400&width=600&text=Checkout+Flow",
    ],
    technologies: ["WordPress", "PHP", "Elementor"],
    year: "2024",
    liveUrl: "https://caketown.infinityfreeapp.com/",
    // githubUrl: "https://github.com/farwa/ecommerce",
  },
  // {
  //   id: "14",
  //   title: "Restaurant Website",
  //   description: "Responsive website for a local restaurant with online ordering, beautiful and functional.",
  //   category: "websites",
  //   image: "/placeholder.svg?height=300&width=400",
  //   images: [
  //     "/placeholder.svg?height=400&width=600&text=Restaurant+Homepage",
  //     "/placeholder.svg?height=400&width=600&text=Menu+Page",
  //     "/placeholder.svg?height=400&width=600&text=Online+Ordering",
  //   ],
  //   technologies: ["React", "Node.js", "MongoDB", "CSS"],
  //   year: "2024",
  //   liveUrl: "https://example-restaurant.com",
  // },
  // {
  //   id: "15",
  //   title: "Portfolio Website",
  //   description: "Personal portfolio website for a photographer, showcasing stunning visuals.",
  //   category: "websites",
  //   image: "/placeholder.svg?height=300&width=400",
  //   images: [
  //     "/placeholder.svg?height=400&width=600&text=Photographer+Portfolio+Home",
  //     "/placeholder.svg?height=400&width=600&text=Gallery+Page",
  //   ],
  //   technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
  //   year: "2023",
  //   liveUrl: "https://photographer-portfolio.com",
  // },
  // {
  //   id: "16",
  //   title: "SaaS Dashboard",
  //   description: "Modern dashboard for a SaaS application with analytics, intuitive and data-rich.",
  //   category: "websites",
  //   image: "/placeholder.svg?height=300&width=400",
  //   images: [
  //     "/placeholder.svg?height=400&width=600&text=Dashboard+Overview",
  //     "/placeholder.svg?height=400&width=600&text=Analytics+View",
  //   ],
  //   technologies: ["React", "TypeScript", "Chart.js", "Material-UI"],
  //   year: "2023",
  //   liveUrl: "https://saas-dashboard.com",
  // },
]
