export interface PortfolioItem {
  id: string
  title: string
  description: string
  category: "figma" |"figmas" | "logos" | "posters" | "social-media" | "presentations" | "websites"
  image: string
  images?: string[]
  video?: string // <--- Add this
  technologies: string[]
  year: string
  liveUrl?: string
  githubUrl?: string
}

export const portfolioData: PortfolioItem[] = [
  // Logos
  {
    id: "1",
    title: "Beads Shop Logo – Classic Design",
    description: "Elegant and handcrafted logo design tailored for a beads shop, highlighting the artistry and cultural roots of traditional jewelry.",
    category: "logos",
    image: "/logo1.webp?height=300&width=400",
    technologies: ["Adobe Illustrator", "Canva"],
    year: "2024",
  },
  {
    id: "2",
    title: "Beads Shop Logo – Modern Identity",
    description: "Contemporary brand identity concept for a beads shop, combining minimalism with vibrant color tones to appeal to modern customers.",
    category: "logos",
    image: "/logo2.webp?height=300&width=400",
    technologies: ["Adobe Illustrator", "Photoshop"],
    year: "2024",
  },
  {
    id: "3",
    title: "Jabon de Lofah – Organic Soap Logo",
    description: "Fresh and natural logo design for Jabon de Lofah, an organic soap brand, reflecting purity, wellness, and eco-friendly values.",
    category: "logos",
    image: "/logo3.webp?height=300&width=400",
    technologies: ["Figma", "Adobe Illustrator"],
    year: "2023",
  },

  // Posters
  {
    id: "4",
    title: "Website Development Course Poster",
    description: "Promotional poster designed to attract students for a website development class, showcasing course benefits, duration, and registration details.",
    category: "posters",
    image: "/poster1.webp?height=300&width=400",
    technologies: ["Canva"],
    year: "2024",
  },
  {
    id: "5",
    title: "Get-Together Invitation Poster",
    description: "Creative and lively invitation poster for a friends and family get-together event, featuring playful visuals and an inviting tone.",
    category: "posters",
    image: "/poster2.webp?height=300&width=400",
    technologies: ["Canva"],
    year: "2024",
  },
  {
    id: "6",
    title: "Minimal Wedding Invitation Design",
    description: "A modern and minimalist wedding invitation poster featuring subtle colors, clean layout, and a touch of elegance for a stylish celebration.",
    category: "posters",
    image: "/poster3.webp?height=300&width=400",
    technologies: ["Canva"],
    year: "2023",
  },
  {
    id: "18",
    title: "Canvas Modal UI Mockup",
    description: "Poster-style visual mockup showcasing a canvas modal UI component, demonstrating layout design and interaction flow.",
    category: "posters",
    image: "/poster4.webp?height=300&width=400",
    technologies: ["Adobe Creative Suite"],
    year: "2023",
  },
  // Social Media
  {
    id: "7",
    title: "LinkedIn Post Series",
    description: "Engaging LinkedIn post templates for business content, designed for maximum reach.",
    category: "social-media",
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=400&width=600&text=LinkedIn+Post+1",
      "/placeholder.svg?height=400&width=600&text=LinkedIn+Post+2",
      "/placeholder.svg?height=400&width=600&text=LinkedIn+Post+3",
    ],
    technologies: ["Canva", "Figma"],
    year: "2024",
  },
  {
    id: "8",
    title: "Instagram Story Templates",
    description: "Branded Instagram story templates for social media marketing, dynamic and interactive.",
    category: "social-media",
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=400&width=600&text=Instagram+Story+1",
      "/placeholder.svg?height=400&width=600&text=Instagram+Story+2",
    ],
    technologies: ["Canva", "Adobe Photoshop"],
    year: "2024",
  },
  {
    id: "9",
    title: "Facebook Ad Campaign",
    description: "Social media graphics for Facebook advertising campaign, optimized for conversions.",
    category: "social-media",
    image: "/placeholder.svg?height=300&width=400",
    images: [
      "/placeholder.svg?height=400&width=600&text=Facebook+Ad+1",
      "/placeholder.svg?height=400&width=600&text=Facebook+Ad+2",
    ],
    technologies: ["Canva", "Figma"],
    year: "2023",
  },

  // Presentations
  {
    id: "10",
    title: "Ismail Industries Ltd.",
    description: "Professional presentation for University project , visually compelling and informative.",
    category: "presentations",
    image: "/ismail1.webp?height=300&width=400",
    images: [
      "/ismail1.webp?height=400&width=600&text=Pitch+Deck+Slide+1",
      "/ismail2.webp?height=400&width=600&text=Pitch+Deck+Slide+2",
      "/ismail3.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail4.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail5.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail6.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail7.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail8.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail9.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail10.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail11.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail12.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail13.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail14.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail15.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
      "/ismail16.webp?height=400&width=600&text=Pitch+Deck+Slide+3",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2024",
  },
  {
    id: "11",
    title: "Anger Managment Presentation",
    description: "Anger Management For University Project Showing Visual Representation Of Anger Management",
    category: "presentations",
    image: "/anger1.webp?height=300&width=400",
    images: [
      "/anger1.webp?height=400&width=600&text=Sales+Presentation+1",
      "/anger2.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger3.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger4.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger5.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger6.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger7.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger8.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger9.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger10.webp?height=400&width=600&text=Sales+Presentation+2",
      "/anger11.webp?height=400&width=600&text=Sales+Presentation+2",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2024",
  },
  {
    id: "17",
    title: "Entrepreneurial Product Pitch – Jabon da Lofah",
    description: "A persuasive and visually engaging presentation showcasing the innovation, benefits, and market potential of Jabon da Lofah – a natural exfoliating soap designed for modern self-care.",
    category: "presentations",
    image: "/jabon1.webp?height=300&width=400",
    images: [
      "/jabon1.webp?height=400&width=600&text=Sales+Presentation+1",
      "/jabon2.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon3.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon4.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon5.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon6.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon7.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon8.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon9.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon10.webp?height=400&width=600&text=Sales+Presentation+2",
      "/jabon11c.webp?height=400&width=600&text=Sales+Presentation+2",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2024",
  },
  {
    id: "12",
    title: "Consumer Behavior Analysis – Rooh Afza",
    description: "An insightful presentation exploring consumer preferences, cultural relevance, and purchasing behavior related to Rooh Afza – the iconic herbal drink that has shaped generations of refreshment habits.",
    category: "presentations",
    image: "/rooh1.webp?height=300&width=400",
    images: [
      "/rooh1.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh2.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh3.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh4.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh5.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh6.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh7.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh8.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh9.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh10.webp?height=400&width=600&text=Training+Slides+2",
      "/rooh11.webp?height=400&width=600&text=Training+Slides+2",
    ],
    technologies: ["PowerPoint", "Canva"],
    year: "2023",
  },


  // Websites
  {
    id: "13",
    title: "Cake Town Website ",
    description: "Cke Town website showcasing the product and services they offer, responsive .",
    category: "websites",
    image: "/cake1.webp?height=300&width=400",
    images: [
      "/cake1.webp?height=400&width=600&text=E-commerce+Homepage",
      "/cake2.webp?height=400&width=600&text=Product+Page",
      "/cake3.webp?height=400&width=600&text=Product+Page",
      "/cake4.webp?height=400&width=600&text=Product+Page",
      "/cake5.webp?height=400&width=600&text=Product+Page",
      "/cake6.webp?height=400&width=600&text=Product+Page",
      "/cake7.webp?height=400&width=600&text=Product+Page",
      "/cake8.webp?height=400&width=600&text=Product+Page",
      "/cake9.webp?height=400&width=600&text=Product+Page",
      "/cake10.webp?height=400&width=600&text=Product+Page",
      "/cake11.webp?height=400&width=600&text=Checkout+Flow",
      "/cake12.webp?height=400&width=600&text=Checkout+Flow",
      "/cake13.webp?height=400&width=600&text=Checkout+Flow",
      "/cake14.webp?height=400&width=600&text=Checkout+Flow",
    ],
    technologies: ["WordPress", "PHP", "Elementor"],
    year: "2024",
    liveUrl: "https://caketown.infinityfreeapp.com/",
    // githubUrl: "https://github.com/farwa/ecommerce",
  },

  {
    id: "20",
    title: "Ice Cream Animation",
    description: "A playful and colorful animation showcasing a ice cream unwrapping, designed to highlight motion graphics skills and evoke a fun summer vibe.",
    category: "figma",
    image: "/Screenshot 2025-08-08 211300.webp",
    video: "/Icecream Prototype.mp4", // <--- Path to your video
    technologies: ["Figma", "Framer Motion"],
    liveUrl: "https://www.figma.com/proto/gEoVajmCuDhng31P448NWq/pizza-Prototype?node-id=6-135&p=f&t=rTS9ahKqnvjINQCD-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=6%3A32",
    year: "2024",
  },
  {
    id: "19",
    title: "Pizza Ordering UI – Animated Figma Design",
    description: "An interactive pizza ordering interface built in Figma, featuring smooth transitions, micro-interactions, and modern visual elements to enhance user experience.",
    category: "figma",
    image: "/Screenshot 2025-08-08 211030.webp",
    video: "/b453dfd8-4fbd-4c6a-9621-4f1e9017d178 (online-video-cutter.com).mov", // <--- Path to your video
    technologies: ["Figma", "Framer Motion"],
    liveUrl: "https://www.figma.com/proto/NLMAi95BxeQOQ1UUBk3xRi/Icecream-Prototype?node-id=4-120&p=f&t=4UwtCAT3wkWV1ck0-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=4%3A120",
    year: "2024",
  },
{
    id: "21",
    title: "Logistix Client",
    description: "A clean and professional design project developed for Logistix, focusing on corporate branding and social media presence. The visuals emphasize trust, reliability, and modern logistics solutions, with consistent typography and structured layouts.",
    category: "figmas",
    image: "/brocher2.webp",
    images: [ "brocher2.webp", "brocher.webp","POST 1.webp","POST 2.webp","POST 3.webp","POST 4.webp","POST 5.webp","POST 6.webp","POST 7.webp","POST 8.webp","POST 9.webp","POST 10.webp"],
    technologies: ["Figma"],
    liveUrl: "",
    year: "2024",
},
{
    id: "22",
    title: "APP redesign",
    description: "A modern and intuitive mobile app redesign focused on enhancing user experience and visual appeal. The project showcases sleek UI elements, improved navigation flow, and a consistent design system tailored for e-commerce functionality. ",
    category: "figmas",
    image: "/Screenshot 2025-08-31 145324.webp",
    technologies: ["Figma", "Framer Motion"],
    liveUrl: "",
    year: "2024",
},
  {
    id: "23",
    title: "Cattle Farm Client",
    description: "A vibrant and nature-inspired branding design created for a cattle farm. The project focuses on fresh, organic aesthetics with playful yet professional visuals that highlight the authenticity of farm products.",
    category: "figmas",
    image: "/Section2.webp",
    images: [ "/Section2.webp", "/Instagrampost-4.webp", "/Instagrampost-5.webp", "/Frame3.webp"],
    technologies: ["Figma", "Framer Motion"],
    liveUrl: "",
    year: "2024",
},


  // {
  //   id: "14",
  //   title: "Restaurant Website",
  //   description: "Responsive website for a local restaurant with online ordering, beautiful and functional.",
  //   category: "websites",
  //   image: "/placeholder.svg?height=300&width=400",
  //   images: [
  //     "/placeholder.svg?height=400&width=600&text=Restaurant+Homepage",
  //     "/placeholder.svg?height=400&width=600&text=Menu+Page",
  //     "/placeholder.svg?height=400&width=600&text=Online+Ordering",
  //   ],
  //   technologies: ["React", "Node.js", "MongoDB", "CSS"],
  //   year: "2024",
  //   liveUrl: "https://example-restaurant.com",
  // },
  // {
  //   id: "15",
  //   title: "Portfolio Website",
  //   description: "Personal portfolio website for a photographer, showcasing stunning visuals.",
  //   category: "websites",
  //   image: "/placeholder.svg?height=300&width=400",
  //   images: [
  //     "/placeholder.svg?height=400&width=600&text=Photographer+Portfolio+Home",
  //     "/placeholder.svg?height=400&width=600&text=Gallery+Page",
  //   ],
  //   technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
  //   year: "2023",
  //   liveUrl: "https://photographer-portfolio.com",
  // },
  // {
  //   id: "16",
  //   title: "SaaS Dashboard",
  //   description: "Modern dashboard for a SaaS application with analytics, intuitive and data-rich.",
  //   category: "websites",
  //   image: "/placeholder.svg?height=300&width=400",
  //   images: [
  //     "/placeholder.svg?height=400&width=600&text=Dashboard+Overview",
  //     "/placeholder.svg?height=400&width=600&text=Analytics+View",
  //   ],
  //   technologies: ["React", "TypeScript", "Chart.js", "Material-UI"],
  //   year: "2023",
  //   liveUrl: "https://saas-dashboard.com",
  // },
]
